version: "3.1"
services:
  todo-account-management-api:
    container_name: todo-account-management-api
    build:
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Development
        - BUILD_CONFIGURATION_ARG=Debug
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - todo-network
    depends_on:
      - todo-account-management-dynamodb
  todo-account-management-dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
networks:
  todo-network: